# Generated by Django 4.1.7 on 2023-05-22 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0010_rename_mach_machine_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 22, 12, 32, 37, 606327)
            ),
        ),
    ]
