# Generated by Django 4.1.7 on 2023-06-05 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0021_remove_personnel_typep_personnel_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 5, 15, 53, 58, 402402)
            ),
        ),
    ]
