# Generated by Django 4.1.7 on 2023-06-08 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0049_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="ip",
            field=models.CharField(default="0.0.0.0", max_length=15),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 8, 23, 9, 10, 126158)
            ),
        ),
    ]
