# Generated by Django 4.1.7 on 2023-06-09 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0057_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="etat",
            field=models.CharField(
                choices=[("En ligne", "En ligne"), ("Hors ligne", "Hors ligne")],
                default="En ligne",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 9, 0, 2, 4, 809426)
            ),
        ),
    ]
