# Generated by Django 4.1.7 on 2023-06-09 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0058_machine_etat_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="date_maintenance",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 9, 0, 26, 35, 926411)
            ),
        ),
    ]
