# Generated by Django 4.1.7 on 2023-06-09 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0059_machine_date_maintenance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 9, 0, 30, 16, 196556)
            ),
        ),
    ]
