# Generated by Django 4.1.7 on 2023-06-09 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0062_remove_personnel_type_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="type",
            field=models.CharField(
                choices=[
                    ("Homme", "Homme"),
                    ("Femme", "Femme"),
                    ("Non spécifié", "Non spécifié"),
                ],
                default="Non spécifié",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 9, 1, 12, 21, 681645)
            ),
        ),
    ]
